export default [
  {
    login: 'guillainbisimwa',
    id: 10418211,
    node_id: 'MDQ6VXNlcjEwNDE4MjEx',
    avatar_url: 'https://avatars.githubusercontent.com/u/10418211?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/guillainbisimwa',
    html_url: 'https://github.com/guillainbisimwa',
    followers_url: 'https://api.github.com/users/guillainbisimwa/followers',
    following_url:
      'https://api.github.com/users/guillainbisimwa/following{/other_user}',
    gists_url: 'https://api.github.com/users/guillainbisimwa/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/guillainbisimwa/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/guillainbisimwa/subscriptions',
    organizations_url: 'https://api.github.com/users/guillainbisimwa/orgs',
    repos_url: 'https://api.github.com/users/guillainbisimwa/repos',
    events_url: 'https://api.github.com/users/guillainbisimwa/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/guillainbisimwa/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'chubaquelo',
    id: 12679503,
    node_id: 'MDQ6VXNlcjEyNjc5NTAz',
    avatar_url: 'https://avatars.githubusercontent.com/u/12679503?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/chubaquelo',
    html_url: 'https://github.com/chubaquelo',
    followers_url: 'https://api.github.com/users/chubaquelo/followers',
    following_url:
      'https://api.github.com/users/chubaquelo/following{/other_user}',
    gists_url: 'https://api.github.com/users/chubaquelo/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/chubaquelo/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/chubaquelo/subscriptions',
    organizations_url: 'https://api.github.com/users/chubaquelo/orgs',
    repos_url: 'https://api.github.com/users/chubaquelo/repos',
    events_url: 'https://api.github.com/users/chubaquelo/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/chubaquelo/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Ahmed-Benj',
    id: 35009174,
    node_id: 'MDQ6VXNlcjM1MDA5MTc0',
    avatar_url: 'https://avatars.githubusercontent.com/u/35009174?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Ahmed-Benj',
    html_url: 'https://github.com/Ahmed-Benj',
    followers_url: 'https://api.github.com/users/Ahmed-Benj/followers',
    following_url:
      'https://api.github.com/users/Ahmed-Benj/following{/other_user}',
    gists_url: 'https://api.github.com/users/Ahmed-Benj/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Ahmed-Benj/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Ahmed-Benj/subscriptions',
    organizations_url: 'https://api.github.com/users/Ahmed-Benj/orgs',
    repos_url: 'https://api.github.com/users/Ahmed-Benj/repos',
    events_url: 'https://api.github.com/users/Ahmed-Benj/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Ahmed-Benj/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Mupa1',
    id: 44979953,
    node_id: 'MDQ6VXNlcjQ0OTc5OTUz',
    avatar_url: 'https://avatars.githubusercontent.com/u/44979953?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Mupa1',
    html_url: 'https://github.com/Mupa1',
    followers_url: 'https://api.github.com/users/Mupa1/followers',
    following_url: 'https://api.github.com/users/Mupa1/following{/other_user}',
    gists_url: 'https://api.github.com/users/Mupa1/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Mupa1/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Mupa1/subscriptions',
    organizations_url: 'https://api.github.com/users/Mupa1/orgs',
    repos_url: 'https://api.github.com/users/Mupa1/repos',
    events_url: 'https://api.github.com/users/Mupa1/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Mupa1/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'LamiaSristy',
    id: 56501603,
    node_id: 'MDQ6VXNlcjU2NTAxNjAz',
    avatar_url: 'https://avatars.githubusercontent.com/u/56501603?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/LamiaSristy',
    html_url: 'https://github.com/LamiaSristy',
    followers_url: 'https://api.github.com/users/LamiaSristy/followers',
    following_url:
      'https://api.github.com/users/LamiaSristy/following{/other_user}',
    gists_url: 'https://api.github.com/users/LamiaSristy/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/LamiaSristy/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/LamiaSristy/subscriptions',
    organizations_url: 'https://api.github.com/users/LamiaSristy/orgs',
    repos_url: 'https://api.github.com/users/LamiaSristy/repos',
    events_url: 'https://api.github.com/users/LamiaSristy/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/LamiaSristy/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'martinnajjar12',
    id: 56537131,
    node_id: 'MDQ6VXNlcjU2NTM3MTMx',
    avatar_url: 'https://avatars.githubusercontent.com/u/56537131?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/martinnajjar12',
    html_url: 'https://github.com/martinnajjar12',
    followers_url: 'https://api.github.com/users/martinnajjar12/followers',
    following_url:
      'https://api.github.com/users/martinnajjar12/following{/other_user}',
    gists_url: 'https://api.github.com/users/martinnajjar12/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/martinnajjar12/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/martinnajjar12/subscriptions',
    organizations_url: 'https://api.github.com/users/martinnajjar12/orgs',
    repos_url: 'https://api.github.com/users/martinnajjar12/repos',
    events_url: 'https://api.github.com/users/martinnajjar12/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/martinnajjar12/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Kingobaino1',
    id: 63409868,
    node_id: 'MDQ6VXNlcjYzNDA5ODY4',
    avatar_url: 'https://avatars.githubusercontent.com/u/63409868?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Kingobaino1',
    html_url: 'https://github.com/Kingobaino1',
    followers_url: 'https://api.github.com/users/Kingobaino1/followers',
    following_url:
      'https://api.github.com/users/Kingobaino1/following{/other_user}',
    gists_url: 'https://api.github.com/users/Kingobaino1/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Kingobaino1/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Kingobaino1/subscriptions',
    organizations_url: 'https://api.github.com/users/Kingobaino1/orgs',
    repos_url: 'https://api.github.com/users/Kingobaino1/repos',
    events_url: 'https://api.github.com/users/Kingobaino1/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Kingobaino1/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: '410AngelaVu',
    id: 65039720,
    node_id: 'MDQ6VXNlcjY1MDM5NzIw',
    avatar_url: 'https://avatars.githubusercontent.com/u/65039720?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/410AngelaVu',
    html_url: 'https://github.com/410AngelaVu',
    followers_url: 'https://api.github.com/users/410AngelaVu/followers',
    following_url:
      'https://api.github.com/users/410AngelaVu/following{/other_user}',
    gists_url: 'https://api.github.com/users/410AngelaVu/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/410AngelaVu/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/410AngelaVu/subscriptions',
    organizations_url: 'https://api.github.com/users/410AngelaVu/orgs',
    repos_url: 'https://api.github.com/users/410AngelaVu/repos',
    events_url: 'https://api.github.com/users/410AngelaVu/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/410AngelaVu/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Lau-283',
    id: 71157447,
    node_id: 'MDQ6VXNlcjcxMTU3NDQ3',
    avatar_url: 'https://avatars.githubusercontent.com/u/71157447?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Lau-283',
    html_url: 'https://github.com/Lau-283',
    followers_url: 'https://api.github.com/users/Lau-283/followers',
    following_url:
      'https://api.github.com/users/Lau-283/following{/other_user}',
    gists_url: 'https://api.github.com/users/Lau-283/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Lau-283/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Lau-283/subscriptions',
    organizations_url: 'https://api.github.com/users/Lau-283/orgs',
    repos_url: 'https://api.github.com/users/Lau-283/repos',
    events_url: 'https://api.github.com/users/Lau-283/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Lau-283/received_events',
    type: 'User',
    site_admin: false,
  },
]
