export default {
  login: 'Ramon-Carrillo',
  id: 68085268,
  node_id: 'MDQ6VXNlcjY4MDg1MjY4',
  avatar_url: 'https://avatars.githubusercontent.com/u/68085268?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Ramon-Carrillo',
  html_url: 'https://github.com/Ramon-Carrillo',
  followers_url: 'https://api.github.com/users/Ramon-Carrillo/followers',
  following_url:
    'https://api.github.com/users/Ramon-Carrillo/following{/other_user}',
  gists_url: 'https://api.github.com/users/Ramon-Carrillo/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/Ramon-Carrillo/starred{/owner}{/repo}',
  subscriptions_url:
    'https://api.github.com/users/Ramon-Carrillo/subscriptions',
  organizations_url: 'https://api.github.com/users/Ramon-Carrillo/orgs',
  repos_url: 'https://api.github.com/users/Ramon-Carrillo/repos',
  events_url: 'https://api.github.com/users/Ramon-Carrillo/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/Ramon-Carrillo/received_events',
  type: 'User',
  site_admin: false,
  name: 'Ramon C',
  company: 'Freelance Front End Developer',
  blog: '',
  location: 'Mexico',
  email: null,
  hireable: true,
  bio: 'HTML | CSS | JavaScript | Sass | Gulp \r\n| React | Node',
  twitter_username: 'ramon_de_NL',
  public_repos: 84,
  public_gists: 0,
  followers: 9,
  following: 1,
  created_at: '2020-07-09T21:52:02Z',
  updated_at: '2022-05-26T03:22:19Z',
}
